name: Publish agent toolbox to s3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-agent-toolbox-to-s3:
    name: Publish agent toolbox to s3
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Publish agent toolbox to S3
        run: |
          aws s3 cp --recursive build s3://zebrunner.com-assets/_common/agent/matlab